Make locale setting works on non-Debian
It appears that C.UTF-8 is only available on Debian.  Use en_US.UTF-8
for Fedora.

This is to explicitly avoid use of C or POSIX locale.  Because wget will
convert the C or POSIX string to UTF-8 string, during the conversion,
%2B will be convert to +.  We need a UTF-8 locale to prevent conversion.
And UTF-8 is our default encoding use during development, so it is
better to use UTF-8 in our system as much as possible to avoid potential
issues in the future.

Signed-off-by: Huang, Ying <ying.huang@intel.com>
Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>

diff --git a/bin/lkp b/bin/lkp
--- a/bin/lkp
+++ b/bin/lkp
@@ -1,7 +1,12 @@
 #!/bin/sh
 
-export LC_ALL=C.UTF-8
-export LANG=C.UTF-8
+LOCALE=$(locale -a | grep -i 'C.UTF-\?8\|en_US.UTF-\?8' | head -1)
+[ -z "$LOCALE" ] && {
+	echo 1>&2 "No required locale!  Some functionalities may not work properly"
+	LOCALE=C
+}
+export LC_ALL=$LOCALE
+export LANG=$LOCALE
 
 [ -n "$LKP_SRC" ] ||
 export LKP_SRC=$(dirname $(dirname $(readlink -e -v $0)))
diff --git a/rootfs/addon/etc/init.d/lkp-bootstrap b/rootfs/addon/etc/init.d/lkp-bootstrap
--- a/rootfs/addon/etc/init.d/lkp-bootstrap
+++ b/rootfs/addon/etc/init.d/lkp-bootstrap
@@ -9,11 +9,13 @@
 # Description:       LKP bootstrap
 ### END INIT INFO
 
-# Call this script at boot time.
-# Keep it simple and stupid -- it will be installed in a number of rootfs.
-
-export LC_ALL=C.UTF-8
-export LANG=C.UTF-8
+LOCALE=$(locale -a | grep -i 'C.UTF-\?8\|en_US.UTF-\?8' | head -1)
+[ -z "$LOCALE" ] && {
+	echo 1>&2 "No required locale!  Some functionalities may not work properly"
+	LOCALE=C
+}
+export LC_ALL=$LOCALE
+export LANG=$LOCALE
 
 mkdir /dev/shm/lkp-bootstrap-once 2>/dev/null || exit 0
 
