monitors: show monitor name on kill failure
To help debug issue

/result/will-it-scale/context_switch1-performance/xps/debian-x86_64-2016-07-28.cgz/x86_64-rhel-7.2/gcc-6/52770c37db2c0ee5585dae2de3d19c8453f1e8dc/38/stderr:
 stderr: kill: (763): No such process
 stderr: kill: (792): No such process
 stderr: kill: (802): No such process
 stderr: kill: (815): No such process
 stderr: kill: (875): No such process
 stderr: kill: (885): No such process
 stderr: kill: (905): No such process
 stderr: kill: (925): No such process
 stderr: kill: (945): No such process
 stderr: kill: (763): No such process

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/bin/post-run b/bin/post-run
--- a/bin/post-run
+++ b/bin/post-run
@@ -31,9 +31,9 @@ kill_monitors()
 	local wait_pidfile="$TMP/.pid-wait-monitors"
 	local pids
 
-	for pidfile in $TMP/pid-monitors
+	for pidfile in $TMP/pid-monitor-*
 	do
-		[ -s "$pidfile" ] || break
+		[ -s "$pidfile" ] || continue
 
 		if [ -s "$wait_pidfile" ]; then
 			pids=$(grep -v -x -F -f "$wait_pidfile" "$pidfile")
@@ -42,7 +42,8 @@ kill_monitors()
 		fi
 
 		[ -n "$pids" ] || continue
-		/bin/kill $signal $pids
+		/bin/kill $signal $pids ||
+		echo "failed to kill monitor ${pidfile##*/pid-monitor-}" >&2
 	done
 }
 
@@ -52,7 +53,7 @@ kill_monitors()
 $LKP_SRC/bin/event/wakeup activate-monitor
 $LKP_SRC/bin/event/wakeup post-test
 # 2) most simple monitors run until being killed
-#    => $TMP/pid-monitors
+#    => $TMP/pid-monitor-*
 kill_monitors -INT
 
 wait_for_monitors && sleep 1
