post-run: quiet kill error
The below error messages are due to monitors exit quickly
when pre-condition is not satisfied.

wfg@inn /result/iozone/2HDD-btrfs-cfq/vm-vp-1G/debian-x86_64-2015-02-07.cgz/x86_64-rhel/gcc-6/78d51aee04cd20f540c78f1f98f0f9a762ab697a/3% sort -u stderr
failed to kill monitor bdi_dev_mapping
failed to kill monitor cpufreq-stats
failed to kill monitor cpuidle
failed to kill monitor lock_stat
failed to kill monitor nfsstat
failed to kill monitor numa-meminfo
failed to kill monitor numa-numastat
failed to kill monitor numa-vmstat
failed to kill monitor perf-profile
failed to kill monitor perf-stat
wfg@inn /result/iozone/2HDD-btrfs-cfq/vm-vp-1G/debian-x86_64-2015-02-07.cgz/x86_64-rhel/gcc-6/78d51aee04cd20f540c78f1f98f0f9a762ab697a/3% ls
bdi_dev_mapping    env.yaml         iozone            kmsg.xz             output               sched_debug.json.gz  stderr       umesg
boot-time          heartbeat        iozone.json.gz    latency_stats       proc-stat.gz         slabinfo.gz          stderr.json  vmstat
diskstats.gz       interrupts.gz    iozone.time       latency_stats.json  proc-vmstat.gz       slabinfo.json.gz     stdout       vmstat.json.gz
diskstats.json.gz  interrupts.json  iozone.time.json  matrix.json.gz      proc-vmstat.json.gz  softirqs.gz          time
dmesg.json         iostat.gz        job.sh            meminfo.gz          reproduce.sh         softirqs.json        time.json
dmesg.xz           iostat.json.gz   job.yaml          meminfo.json.gz     sched_debug.gz       stats.json           turbostat

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/bin/post-run b/bin/post-run
--- a/bin/post-run
+++ b/bin/post-run
@@ -30,6 +30,7 @@ kill_monitors()
 	local signal=$1
 	local wait_pidfile="$TMP/.pid-wait-monitors"
 	local pids
+	local pid
 
 	for pidfile in $TMP/pid-monitor-*
 	do
@@ -42,8 +43,13 @@ kill_monitors()
 		fi
 
 		[ -n "$pids" ] || continue
-		/bin/kill $signal $pids ||
-		echo "failed to kill monitor ${pidfile##*/pid-monitor-}" >&2
+
+		for pid in $pids
+		do
+			[ -d /proc/$pid ] || continue
+			/bin/kill $signal $pids ||
+			echo "failed to kill monitor ${pidfile##*/pid-monitor-}" >&2
+		done
 	done
 }
 
