update build-dpdk to handle repo/dpdk/testrepo from dpdk team
Signed-off-by: Philip Li <philip.li@intel.com>
Signed-off-by: Huang, Ying <ying.huang@intel.com>

diff --git a/tests/build-dpdk b/tests/build-dpdk
--- a/tests/build-dpdk
+++ b/tests/build-dpdk
@@ -27,7 +27,7 @@ merge_configs()
 	echo "$lines" > $dot_config
 }
 
-DPDK_SRC=/build/dpdk/src
+DPDK_REPO_ROOT=/build/dpdk/src
 DPDK_OBJ=/build/dpdk/obj
 export RTE_KERNELDIR=/build/linux/src
 
@@ -40,7 +40,7 @@ dpdk_remote=${dpdk_branch%%/*}
 [[ $branch ]] || branch='linus/master'
 remote=${branch%%/*}
 
-check_mount dpdk-src $DPDK_SRC -t tmpfs
+check_mount dpdk-src $DPDK_REPO_ROOT -t tmpfs
 check_mount dpdk-obj $DPDK_OBJ -t tmpfs
 check_mount kernel-src $RTE_KERNELDIR -t tmpfs
 
@@ -51,9 +51,18 @@ make_config allmodconfig || die "make allmodconfig failed"
 make prepare || die "make prepare failed"
 make scripts/ || die "make scripts/ failed"
 
-git_clone_update git://gitmirror/$dpdk_remote $DPDK_SRC || die "failed clone dpdk tree $dpdk_remote"
-cd $DPDK_SRC
+git_clone_update git://gitmirror/$dpdk_remote $DPDK_REPO_ROOT || die "failed clone dpdk tree $dpdk_remote"
+cd $DPDK_REPO_ROOT
 git checkout -q $dpdk_commit || die "failed to checkout dpdk commit $dpdk_commit"
+
+if [ -f Makefile ]; then
+	DPDK_SRC=$DPDK_REPO_ROOT
+else
+	# specific handling of repo/dpdk/testrepo code structure
+	DPDK_SRC=$DPDK_REPO_ROOT/dpdk
+fi
+
+cd $DPDK_SRC
 
 config_file=$LKP_SRC/etc/dpdk-configs/$dpdk_config
 [ -f $config_file ] ||
@@ -69,6 +78,7 @@ grep -r -l 'Werror' $DPDK_SRC | xargs sed -i 's/ -Werror//'
 
 make O=$DPDK_OBJ DESTDIR=$RESULT_ROOT
 
+cd $DPDK_REPO_ROOT
 git reset --hard
 
 build_complete
