use cmd to record reproduce for build-dpdk test
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/build-dpdk b/tests/build-dpdk
--- a/tests/build-dpdk
+++ b/tests/build-dpdk
@@ -44,46 +44,36 @@ check_mount dpdk-src $DPDK_REPO_ROOT -t tmpfs
 check_mount dpdk-obj $DPDK_OBJ -t tmpfs
 check_mount kernel-src $RTE_KERNELDIR -t tmpfs
 
-git_clone_update git://gitmirror/$remote $RTE_KERNELDIR || die "failed clone kernel tree $remote"
-cd $RTE_KERNELDIR
+cmd git_clone_update git://gitmirror/$remote $RTE_KERNELDIR || die "failed clone kernel tree $remote"
+cmd cd $RTE_KERNELDIR
 git checkout -q $commit || die "failed to checkout kernel commit $_commit"
 make_config allmodconfig || die "make allmodconfig failed"
-make prepare || die "make prepare failed"
-make scripts/ || die "make scripts/ failed"
+cmd make prepare || die "make prepare failed"
+cmd make scripts/ || die "make scripts/ failed"
 
 rm -fr "$DPDK_REPO_ROOT" 2>/dev/null
-git_clone_update git://gitmirror/$dpdk_remote $DPDK_REPO_ROOT || die "failed clone dpdk tree $dpdk_remote"
-cd $DPDK_REPO_ROOT
-git checkout -q $dpdk_commit || die "failed to checkout dpdk commit $dpdk_commit"
+cmd git_clone_update git://gitmirror/$dpdk_remote $DPDK_REPO_ROOT || die "failed clone dpdk tree $dpdk_remote"
+cmd cd $DPDK_REPO_ROOT
+cmd git checkout -q $dpdk_commit || die "failed to checkout dpdk commit $dpdk_commit"
 
 cd $DPDK_REPO_ROOT
 
 config_file=$LKP_SRC/etc/dpdk-configs/$dpdk_config
-[ -f $config_file ] ||
-config_file=$DPDK_REPO_ROOT/config/defconfig_$dpdk_config
+[ -f $config_file ] || config_file=$DPDK_REPO_ROOT/config/defconfig_$dpdk_config
 [ -f $config_file ] || die "invalid config file $config_file"
 
-make O=$DPDK_OBJ T=$ARCH-native-linuxapp-$dpdk_compiler_name config || die "failed to make config"
+cmd make O=$DPDK_OBJ T=$ARCH-native-linuxapp-$dpdk_compiler_name config || die "failed to make config"
 
 [[ $config_file =~ "$DPDK_REPO_ROOT/config" ]] ||
 merge_configs $config_file
 
 grep -r -l 'Werror' $DPDK_REPO_ROOT | xargs sed -i 's/ -Werror//'
 
-echo "$(date +'%F %T') cat $DPDK_OBJ/.config start"
-cat $DPDK_OBJ/.config
-echo "cat $DPDK_OBJ/.config end"
+cp $DPDK_OBJ/.config $RESULT_ROOT/dpdk_config
 
-make O=$DPDK_OBJ DESTDIR=$RESULT_ROOT
-make_exit_status=$?
+cmd make O=$DPDK_OBJ DESTDIR=$RESULT_ROOT
+build_complete $?
 
 git reset --hard
 
-build_complete
-
-if [[ $make_exit_status = 0 ]]; then
-	echo "$testcase success"
-else
-	echo "$testcase fail $make_exit_status"
-fi
-exit $make_exit_status
+exit 0
