build-dpdk: support kernel commit
Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>

diff --git a/tests/build-dpdk b/tests/build-dpdk
--- a/tests/build-dpdk
+++ b/tests/build-dpdk
@@ -3,12 +3,16 @@
 # - dpdk_commit
 # - dpdk_config
 # - dpdk_compiler
+# - branch
+# - commit
 
 ## DPDK is a set of libraries and drivers for fast packet processing.
 ## It was designed to run on any processors knowing Intel x86 has
 ## been the first CPU to be supported. Ports for other CPUs like
 ## IBM Power 8 are under progress. It runs mostly in Linux userland.
 ## A FreeBSD port is now available for a subset of DPDK features.
+
+shopt -s nullglob
 
 . $LKP_SRC/lib/debug.sh
 . $LKP_SRC/lib/mount.sh
@@ -22,31 +26,39 @@ merge_configs()
 	echo "$lines" > $dot_config
 }
 
-config_file=(
-		$LKP_SRC/etc/dpdk-configs/$dpdk_config
-		$SRC_ROOT/config/defconfig_$dpdk_config
-)
-[[ $config_file ]] || die "invalid config file $config_file"
+config_file=$LKP_SRC/etc/dpdk-configs/$dpdk_config
+[ -f $config_file ] ||
+config_file=$SRC_ROOT/config/defconfig_$dpdk_config
+[ -f $config_file ] || die "invalid config file $config_file"
 
 SRC_ROOT=/build/dpdk/src
 OBJ_ROOT=/build/dpdk/obj
+export RTE_KERNELDIR=/build/linux/src
+
 ARCH=${dpdk_config%%-*}
 dpdk_compiler_name=${dpdk_compiler%%-*}
 
 [[ $dpdk_branch ]] || dpdk_branch='dpdk/master'
 dpdk_remote=${dpdk_branch%%/*}
 
+[[ $branch ]] || branch='linus/master'
+remote=${branch%%/*}
+
 check_mount dpdk-src $SRC_ROOT -t tmpfs
 check_mount dpdk-obj $OBJ_ROOT -t tmpfs
+check_mount kernel-src $RTE_KERNELDIR -t tmpfs
 
-git_clone_update git://gitmirror/$dpdk_remote $SRC_ROOT || die "failed clone dpdk tree"
-git checkout $dpdk_commit || die "failed to checkout commit $dpdk_commit"
+git_clone_update git://gitmirror/$remote $RTE_KERNELDIR || die "failed clone kernel tree $remote"
+cd $RTE_KERNELDIR
+git checkout $commit || die "failed to checkout kernel commit $_commit"
 
-export RTE_KERNELDIR=/usr/src/kernels/3.19.5-100.fc20.x86_64/
+git_clone_update git://gitmirror/$dpdk_remote $SRC_ROOT || die "failed clone dpdk tree $dpdk_remote"
+cd $SRC_ROOT
+git checkout $dpdk_commit || die "failed to checkout dpdk commit $dpdk_commit"
 
 make O=$OBJ_ROOT config T=$ARCH-native-linuxapp-$dpdk_compiler_name || die "failed to make config"
 
 [[ $config_file =~ "$SRC_ROOT/config" ]] ||
 merge_configs $config_file
 
-make O=$OBJ_ROOT DESTDIR=$RESULT_ROOT || die "make failed"
+make O=$OBJ_ROOT DESTDIR=$RESULT_ROOT install || die "make failed"
