install-iso-pre: some optimize
[Why]
1. because of commit id: dfd23bd50952e723d1a87d23324a0b2ae2807813, we
   need do the following actions for submit job:
   - install diffutils pkg.
   - let LKP_SRC be a git dir.

2. 10G sometime is not enough for some os installation, so we increase
   it to 30G.

3. Remove some kernel parameters that are useless during iso
   installation.

4. testbox is not always equals to testbox, so specific the queue field
   when submit.

Signed-off-by: Yu Chuan <13186087857@163.com>

diff --git a/tests/install-iso-pre b/tests/install-iso-pre
--- a/tests/install-iso-pre
+++ b/tests/install-iso-pre
@@ -66,7 +66,7 @@ create_lv()
 {
 	log_info "start create lv:$LV_NAME"
 
-	lvcreate -y -L 10G -n ${LV_NAME} ${VG_NAME} || die "create logical volume failed."
+	lvcreate -y -L 30G -n ${LV_NAME} ${VG_NAME} || die "create logical volume failed."
 
 	mkfs.ext4 /dev/mapper/${VG_NAME}-${LV_NAME}
 }
@@ -148,6 +148,10 @@ prepare_submit()
 	mkdir -p $CCI_REPOS && cd $CCI_REPOS
 	git clone $LAB_Z9_URL || die "clone lab-z9 git repo failed: $LAB_Z9_URL"
 
+	git clone https://gitee.com/wu_fengguang/lkp-tests.git
+	cp -a $LKP_SRC/. ./lkp-tests/
+	export LKP_SRC=$(realpath ./lkp-tests/)
+
 	local config_yaml="/etc/compass-ci/defaults/sparrow.yaml"
 	mkdir -p $(dirname $config_yaml)
 	cat >> $config_yaml <<-EOF
@@ -171,7 +175,7 @@ prepare_install_iso_yaml()
 	custom_ipxe="#!ipxe\\\\n"
 	custom_ipxe="${custom_ipxe}\\\\ndhcp"
 	custom_ipxe="${custom_ipxe}\\\\ninitrd ${tftp_root}/initrd.img"
-	custom_ipxe="${custom_ipxe}\\\\nkernel ${tftp_root}/vmlinuz ro inst.geoloc=0 console=ttyS0 smmu.bypassdev=0x1000:0x17 smmu.bypassde1000:0x15 viff video=VGA-1:640x480-32@60me initrd=initrd.img ip=dhcp inst.ks=http://${HTTP_SERVER_HOST}:${HTTP_SERVER_PORT}/os/install/ks/${iso_os}_${iso_arch}_${iso_version}.ks"
+	custom_ipxe="${custom_ipxe}\\\\nkernel ${tftp_root}/vmlinuz ro console=ttyS0 initrd=initrd.img ip=dhcp inst.ks=http://${HTTP_SERVER_HOST}:${HTTP_SERVER_PORT}/os/install/ks/${iso_os}_${iso_arch}_${iso_version}.ks"
 	custom_ipxe="${custom_ipxe}\\\\nboot\\\\n"
 
 	log_info "custom_ipxe: $custom_ipxe"
@@ -189,6 +193,7 @@ submit_install_iso_yaml()
 
 	${LKP_SRC}/sbin/submit \
 		${install_iso_yaml} \
+		queue=$queue \
 		testbox=$testbox || die "submit ${install_iso_yaml} failed"
 }
 
@@ -212,6 +217,7 @@ submit_install_iso_firstboot_yaml()
 		${firstboot_yaml} \
 		suite=install-iso-firstboot \
 		group_id=${group_id} \
+		queue=$queue \
 		testbox=$testbox || die "submit ${firstboot_yaml} failed"
 }
 
@@ -232,6 +238,7 @@ submit_install_iso_sync_rootfs_yaml()
 		install-iso-sync-rootfs.NFS_SERVER_HOST=${NFS_SERVER_HOST} \
 		install-iso-sync-rootfs.NFS_ROOT_DIR=${NFS_ROOT_DIR} \
 		install-iso-sync-rootfs.VG_NAME=${VG_NAME} \
+		queue=$queue \
 		testbox=$testbox || die "submit job failed: ${sync_rootfs_yaml}"
 }
 
