tests/iozone: explicit support test=all and add invalid test option identification
[example]

iozone-bs.yaml

...
suite: iozone
category: benchmark

file_size: 4g
test: all

block_size:
- 64k
...

[output]

	...
	Run began: Sat Nov 21 16:48:22 2020

	Record Size 64 kB
	File size set to 4194304 kB
	Command line used: iozone -r 64k -s 4g -f /fs/sdb/iozonetest
	Output is in kBytes/sec
	Time Resolution = 0.000001 seconds.
	Processor cache size set to 1024 kBytes.
	Processor cache line size set to 32 bytes.
	File stride size set to 17 * record size.
                                                              random    random     bkwd    record    stride
              kB  reclen    write  rewrite    read    reread    read     write     read   rewrite      read   fwrite frewrite    fread  freread
         4194304      64 13650392 11529057  7878373  7763936  7166639 10774159  7520609  16188351   7362482  9751567  9453804  7981606  7932187

diff --git a/tests/iozone b/tests/iozone
--- a/tests/iozone
+++ b/tests/iozone
@@ -19,6 +19,8 @@ if [ -n "$block_size" ]; then
 	for ele in ${array[@]}
 	do
 		case $ele in
+			"all")       args+=" -a"
+				;;
 			"write")     args+=" -i 0"
 				;;
 			"read")      args+=" -i 1"
@@ -44,6 +46,9 @@ if [ -n "$block_size" ]; then
 			"pwritev")   args+=" -i 11"
 				;;
 			"preadv")    args+=" -i 12"
+				;;
+			*) echo "invalid test option, please check again!"
+				exit 1
 				;;
 		esac
 	done
