tests/iozone: refactor format optimization
Signed-off-by: Lu Kaiyi <2392863668@qq.com>

diff --git a/tests/iozone b/tests/iozone
--- a/tests/iozone
+++ b/tests/iozone
@@ -47,8 +47,7 @@ if [ -n "$block_size" ]; then
 				;;
 			"preadv")    args+=" -i 12"
 				;;
-			*) echo "invalid test option, please check again!"
-				exit 1
+			*)           echo "invalid test option, please check again!" && exit 1
 				;;
 		esac
 	done
