iso2rootfs: add three required fields when submit test job.yaml
[Why]
Since the ability `verify account information` was added on submit
job.yaml, so add three required fields when submit test job.yaml.

Signed-off-by: Yu Chuan <13186087857@163.com>

diff --git a/tests/iso2rootfs b/tests/iso2rootfs
--- a/tests/iso2rootfs
+++ b/tests/iso2rootfs
@@ -448,11 +448,21 @@ EOF
 ############ submit test job yaml ############
 generate_global_yaml()
 {
+	[ -n "${submit_email}" ] || die "cannot find value of var: submit_email"
+	[ -n "${submit_name}" ] || die "cannot find value of var: submit_name"
+	[ -n "${submit_uuid}" ] || die "cannot find value of var: submit_uuid"
+
 	local config_yaml="/etc/compass-ci/defaults/sparrow.yaml"
 
 	mkdir -p "$(dirname "${config_yaml}")"
-	echo "SCHED_HOST: ${SCHED_HOST}" >> "${config_yaml}"
-	echo "SCHED_PORT: ${SCHED_PORT}" >> "${config_yaml}"
+
+	cat <<-EOF > "${config_yaml}"
+	SCHED_HOST: ${SCHED_HOST}
+	SCHED_PORT: ${SCHED_PORT}
+	my_email: ${submit_email}
+	my_name: ${submit_name}
+	my_uuid: ${submit_uuid}
+	EOF
 }
 
 generate_submit_append_str()
