tests: use die to exit when basic requirements not met
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/kbuild b/tests/kbuild
--- a/tests/kbuild
+++ b/tests/kbuild
@@ -19,7 +19,7 @@ run_kbuild()
 	start_time=$(date +%s)
 	iterations=0
 	while true; do
-		log_cmd make mrproper || die "make mrproper failed" 
+		log_cmd make mrproper || die "make mrproper failed"
 		log_cmd make $build_kconfig || die "make $build_kconfig failed"
 		log_cmd make -j $nr_task $target 2> /dev/null || die "make -j $nr_task $target failed"
 		iterations=$((iterations + 1))
@@ -30,9 +30,6 @@ run_kbuild()
 	echo "runtime: $((now - start_time))"
 }
 
-cd $BENCHMARK_ROOT/kbuild/linux || {
-	echo "ERROR: no kernel source code in $BENCHMARK_ROOT/kbuild/linux" 1>&2
-	exit 1
-}
+cd $BENCHMARK_ROOT/kbuild/linux || die "no kernel source code in $BENCHMARK_ROOT/kbuild/linux"
 
 run_kbuild
diff --git a/tests/kernbench b/tests/kernbench
--- a/tests/kernbench
+++ b/tests/kernbench
@@ -2,14 +2,10 @@
 # - nr_loops
 # - nr_threads
 
-cd $BENCHMARK_ROOT/kernbench || {
-	echo "ERROR: kernbench benchmark is not installed yet!" >&2
-	exit 1
-}
+. $LKP_SRC/lib/reproduce-log.sh
 
-cd linux || {
-	echo "ERROR: linux kernel source not found!" >&2
-	exit 1
-}
+cd $BENCHMARK_ROOT/kernbench || die "kernbench benchmark is not installed yet"
+
+cd linux || die "linux kernel source not found"
 
 ../kernbench -n $nr_loops -o $nr_threads -H -M
diff --git a/tests/mce-test b/tests/mce-test
--- a/tests/mce-test
+++ b/tests/mce-test
@@ -7,13 +7,15 @@
 
 shopt -s nullglob
 
-[ -n "$mount_points" ] || die "\"mount_points\" is empty"
-
-cd "$BENCHMARK_ROOT"/mce-test || exit
-
 . "$LKP_SRC"/lib/upload.sh
 . "$LKP_SRC"/lib/job.sh
 . "$LKP_SRC"/lib/debug.sh
+. $LKP_SRC/lib/reproduce-log.sh
+
+[ -n "$mount_points" ] || die "\"mount_points\" is empty"
+
+cd $BENCHMARK_ROOT/mce-test || die "no $BENCHMARK_ROOT/mce-test"
+
 read_env_vars
 exit_value=0
 
@@ -111,9 +113,7 @@ test_choice()
 		if grep -q "^$i" "$MCE_SCENARIO_DIR"/*; then
 			grep -h "^$i" "$MCE_SCENARIO_DIR"/* | awk '{print $1" "$2}' >> $MCE_CASELIST
 		else
-			echo "mce test case: $i not found"
-			exit_value=1
-			return
+			die "mce test case: $i not found"
 		fi
 	done
 
@@ -121,7 +121,6 @@ test_choice()
 		create_edac_ref
 	fi
 	./runmcetest -t $MCE_TMPDIR -s $MCE_SUMDIR -o $MCE_LOGDIR -b $MCE_TOOLDIR -l $MCE_CASELIST -r 1
-	exit_value=$?
 
 	#upload_files -t results  $MCE_LOGDIR/*
 
@@ -140,4 +139,4 @@ else
 	test_choice
 fi
 
-exit $exit_value
+exit 0
