tests/kernel_selftests: fix compilation error of bpf and gpio
/result/kernel_selftests/defaults/vm-lkp-a08/debian-x86_64-2016-08-31.cgz/x86_64-rhel-7.2/gcc-6/v4.10-rc3/1
	stderr:  #include <linux/bpf_perf_event.h>
	stderr:                                   ^
	stderr: compilation terminated.
	stderr: make[1]: *** [test_verifier] Error 1
	stderr: make[2]: *** ../../../gpio: No such file or directory.  Stop.
	stderr: make[1]: *** [../../../gpio/gpio-utils.o] Error 2

Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/kernel_selftests b/tests/kernel_selftests
--- a/tests/kernel_selftests
+++ b/tests/kernel_selftests
@@ -19,13 +19,13 @@ echo "KERNEL SELFTESTS: linux_headers_dir is $linux_headers_dir"
 
 # linux-selftests file is created by 0day system, and located in /usr/src/linux-selftests-$kconfig-$commit directory.
 linux_selftests_dir=(/usr/src/linux-selftests-*)
+[[ $linux_selftests_dir ]] || die "failed to find linux-selftests dir"
 
-if [[ $linux_selftests_dir ]]; then
-	cd $linux_selftests_dir
-	log_cmd make || die "failed to run make"
-else
-	cd $BENCHMARK_ROOT/kernel_selftests || die "can not find benchmark dir"
-fi
+# headers_install's default location is usr/include which is required by several tests' Makefile
+mkdir -p "$linux_selftests_dir/usr/include" || die
+mount --bind $linux_headers_dir/include $linux_selftests_dir/usr/include || die
+
+cd $linux_selftests_dir/tools/testing/selftests || die
 
 # workaround hugetlbfstest.c open_file() error
 mkdir -p /hugepages
@@ -51,5 +51,7 @@ for mf in */Makefile; do
 			mount -t efivarfs efivarfs /sys/firmware/efi/efivars
 			;;
 	esac
-	log_cmd make run_tests -C $subtest -I $linux_headers_dir/include -I $linux_headers_dir/include/uapi
+
+	echo
+	log_cmd make run_tests -C $subtest
 done
