tests/kvm-unit-tests: fix SKIP pmu (/proc/sys/kernel/nmi_watchdog not equal to 0)
Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/kvm-unit-tests b/tests/kvm-unit-tests
--- a/tests/kvm-unit-tests
+++ b/tests/kvm-unit-tests
@@ -10,6 +10,12 @@
 . $LKP_SRC/lib/debug.sh
 . $LKP_SRC/lib/upload.sh
 
+setup_test_environment()
+{
+	# fix "SKIP pmu (/proc/sys/kernel/nmi_watchdog not equal to 0)"
+	echo 0 > /proc/sys/kernel/nmi_watchdog
+}
+
 cd $BENCHMARK_ROOT/kvm-unit-tests || exit
 
 [ -c '/dev/kvm' ] || {
@@ -29,6 +35,8 @@ else
 		exit 1
 	fi
 fi
+
+setup_test_environment || die "failed to setup test environment"
 
 log_cmd ./run_tests.sh || {
 	exit_code=$?
