ltp: fix ltp/commands/mail: Mailer daemon can't report failure to root
        fix the following issue:  When mail fail to deliver the mail. Mailer daemon should report this failure to root.
        -----------
        ltp/commands: mail_tests::mail02    2  TFAIL  :  ltpapicmd.c:156: Test #2: No new mail for root. Reason:
                      mail_tests::mail03    3  TFAIL  :  ltpapicmd.c:156: Test #3: No new mail for root. Reason:
        -----------
        We need to install postfix and fix the config file to report the failure to root.

Signed-off-by: Shaoting Lei <leist.fnst@cn.fujitsu.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/ltp b/tests/ltp
--- a/tests/ltp
+++ b/tests/ltp
@@ -65,6 +65,27 @@ specify_tmpdir()
 	return 0
 }
 
+make_configfile()
+{
+       [ -f "$CONFIG_FILE" ] || return
+       cp $CONFIG_FILE $CONFIG_FILE.ltpback
+       grep -q "default_transport = error" $CONFIG_FILE || {
+           echo "default_transport = error" >> $CONFIG_FILE
+           /etc/init.d/postfix reload || return
+           sleep 2
+           systemctl restart postfix || return
+           sleep 3
+       }
+      
+       return 0
+}
+
+recover_configfile()
+{
+      [ -f "$CONFIG_FILE" ] || return
+      cp $CONFIG_FILE.ltpback $CONFIG_FILE
+}
+
 workaround_env
 
 case "$test" in
@@ -93,7 +114,9 @@ commands)
 		done
 		systemctl restart nscd || exit
 	}
-	;;
+        CONFIG_FILE="/etc/postfix/main.cf"
+        make_configfile || exit
+        ;;
 dio)
 	[ -z "$mount_points" ] && exit
 	export TMPDIR="${mount_points%% *}"
@@ -150,6 +173,10 @@ check_ignored_cases $test
 log_cmd ./runltp -f $test $big_dev_opt $tmpdir_opt || exit
 
 exit_value=$?
+
+[ "$test" == "commands" ] && {
+     recover_configfile || exit
+}
 
 upload_files -t results $BENCHMARK_ROOT/ltp/results/* \
 	$BENCHMARK_ROOT/ltp/output
