tests/makepkg-deps: mount DEPS_MNT to LKP_SERVER if exists
Reviewed-by: "Huang, Ying" <ying.huang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/makepkg-deps b/tests/makepkg-deps
--- a/tests/makepkg-deps
+++ b/tests/makepkg-deps
@@ -13,7 +13,9 @@ DISTRO=${rootfs%%-*}
 
 DEPS_MNT=/osimage/deps
 mkdir -p "$DEPS_MNT"
-# mount $LKP_SERVER:$DEPS_MNT $DEPS_MNT || die "Failed to run mount"
+if [ -n "$LKP_SERVER" ]; then
+	mount $LKP_SERVER:$DEPS_MNT $DEPS_MNT || die "Failed to run mount"
+fi
 
 umask 002
 
