cmd: rename to log_cmd
Most people will possibly puzzle at what "cmd" means.

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/packetdrill b/tests/packetdrill
--- a/tests/packetdrill
+++ b/tests/packetdrill
@@ -9,5 +9,5 @@ cd $BENCHMARK_ROOT/packetdrill || exit
 for f in $(find . -name "*.pkt" ! -name "*diag-ipv6*" | sort); do
 	echo "Running $f ..."
 	ip tcp_metrics flush all > /dev/null 2>&1
-	cmd ./packetdrill $f || echo "$f failed"
+	log_cmd ./packetdrill $f || echo "$f failed"
 done
