tests/rcurefscale: add more parameters supported
lizhijian@inn:/result/rcurefscale/10000-50%-30-0-refcnt-ucode=0x5003006/lkp-csl-2sp8/debian-10.4-x86_64-20200603.cgz/x86_64-rhel-8.3-customedconfig-rcurefscale/gcc-9/64570fbc14f8d7cb3fe3995f20e26bc25ce4b2cc/1$
cat rcurefscale.json
{
  "rcurefscale.refcnt-ref-scale.duration_per_loop.ns": [
    2262.4440666666665
  ]
}
lizhijian@inn:/result/rcurefscale/10000-50%-30-0-lock-irq-ucode=0x5003006/lkp-csl-2sp8/debian-10.4-x86_64-20200603.cgz/x86_64-rhel-8.3-customedconfig-rcurefscale/gcc-9/64570fbc14f8d7cb3fe3995f20e26bc25ce4b2cc/0$
cat rcurefscale.json
{
  "rcurefscale.lock-irq-ref-scale.duration_per_loop.ns": [
    14812.310833333333
  ]
}

NOTE: it's observed that some parmeters will cause the results missing
since the buffer of kernel printk overflow in below code:
730     for (exp = 0; exp < nruns; exp++) {
731         u64 avg;
732         u32 rem;
733
734         avg = div_u64_rem(result_avg[exp], 1000, &rem);
735         sprintf(buf1, "%d\t%llu.%03u\n", exp + 1, avg, rem);
736         strcat(buf, buf1);
737     }
if we specified nruns to 300, the strlen(buf) > 800, then the result will
be missing or incompleted like:
[   53.521455] rcu-ref-scale: END OF TEST. Calculating average duration per loop (nanoseconds)...
[   53.531191] rcu-ref-scale:
               Runs     Time(ns)
               1        34.912
               2        34.534
               3        34.871
               4        34.757
...
               90       34.813
               91       34.445
               92       34.403
               93       34.538
               94       34.616
               95       34.725
               96  <<<<<< incompleted result

I'm trying to fix this issue

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/rcurefscale b/tests/rcurefscale
--- a/tests/rcurefscale
+++ b/tests/rcurefscale
@@ -1,10 +1,22 @@
 #!/bin/sh
+# - nr_threads
+# - scale_type
+# - loops
+# - readdelay
+# - nruns
 
 ## creates an rcurefscale kernel module that can be loaded to
 ## run a torture test.
 
 . $LKP_SRC/lib/debug.sh
 . $LKP_SRC/lib/reproduce-log.sh
+
+args=""
+[ ! -z "$scale_type" ] && args="$args scale_type=$scale_type"
+[ ! -z "$nr_threads" ] && args="$args nreaders=$nr_threads"
+[ ! -z "$loops" ] && args="$args loops=$loops"
+[ ! -z "$readdelay" ] && args="$args readdelay=$readdelay"
+[ ! -z "$nruns" ] && args="$args nruns=$nruns"
 
 wait_for_refscale_completion()
 {
@@ -14,7 +26,7 @@ wait_for_refscale_completion()
 	done
 }
 
-log_cmd modprobe refscale || die "failed to load refscale module, try to enable CONFIG_RCU_REF_SCALE_TEST and build rcurefscale.ko"
+log_cmd modprobe refscale $args || die "failed to load refscale module, try to enable CONFIG_RCU_REF_SCALE_TEST and build rcurefscale.ko"
 
 wait_for_refscale_completion
 
