tests/rpmbuild: use user lkp to build SRPMS
[why]
use root to build SRPMS may cause some problems, such as build mysql

$ rpmbuild -ba mysql.spec
mysql's regression tests fail if run as root. If you really need to
build the RPM as root, use --nocheck to skip the regression tests.

it's not proper to build without tests, so now use regular user lkp
to build SRPMS

Signed-off-by: Wang Yong <wangyong0117@qq.com>

diff --git a/tests/rpmbuild b/tests/rpmbuild
--- a/tests/rpmbuild
+++ b/tests/rpmbuild
@@ -151,12 +151,12 @@ install_srpm()
 {
 	add_user_mock
 
-	rpm -i --nosignature "${repo_addr}/${upstream_repo}" >/dev/null || die "failed to install source rpm: ${repo_addr}/${upstream_repo}"
+	su lkp -c "rpm -i --nosignature ${repo_addr}/${upstream_repo} >/dev/null" || die "failed to install source rpm: ${repo_addr}/${upstream_repo}"
 }
 
 build_rpm()
 {
-	local spec_dir="${HOME}/rpmbuild/SPECS"
+	export spec_dir="/home/lkp/rpmbuild/SPECS"
 	[ -n "$package_name" ] &&
 		{
 			# HTTP is proxy cache friendly
@@ -173,7 +173,7 @@ build_rpm()
 			spectool -g -R "$spec_dir/"*.spec || die "failed to download source file"
 		}
 	# Build source and binary packages
-	rpmbuild -ba "$spec_dir"/*.spec || die "failed to build rpms"
+	su lkp -c "rpmbuild -ba ${spec_dir}/*.spec" || die "failed to build rpms"
 	endTime=$(date +%Y-%m-%d-%H:%M)
 	endTime_s=$(date +%s)
 
@@ -184,12 +184,12 @@ build_rpm()
 
 show_rpm_files()
 {
-	find ${HOME}/rpmbuild/RPMS -type f -name "*.rpm"
+	find /home -type f -name "*.rpm" | grep -v src.rpm
 }
 
 show_src_rpm_files()
 {
-	find ${HOME}/rpmbuild/SRPMS -type f -name "*.rpm"
+	find /home -type f -name "*.src.rpm"
 }
 
 show_spec_file()
