tests/rpmbuild-pkg: change the way obtaining spec file
[why]
tests/rpmbuild-pkg: package_name=${upstream_repo##*/}
when the package name is inconsistent with the repo name, it will cause
the error like:

+ grep http -rl /root/rpmbuild/SPECS/zstd-test.spec
grep: /root/rpmbuild/SPECS/zstd-test.spec: No such file or directory

+ spectool -g -R /root/rpmbuild/SPECS/zstd-test.spec
Can't open '/root/rpmbuild/SPECS/zstd-test.spec': No such file or
directory at /usr/bin/spectool line 314.

Signed-off-by: Li Ping <1477412247@qq.com>

diff --git a/tests/rpmbuild-pkg b/tests/rpmbuild-pkg
--- a/tests/rpmbuild-pkg
+++ b/tests/rpmbuild-pkg
@@ -49,7 +49,7 @@ init_workspace()
 
 download_upstream_repo()
 {
-	local url="git://${GIT_SERVER}/openeuler/${upstream_repo}"
+	local url="git://${GIT_SERVER}/${upstream_dir}/${upstream_repo}"
 
 	git clone "$url" || die "clone git repo ${package_name} failed: $url"
 	cd "$package_name" || exit
@@ -75,14 +75,14 @@ build_rpm()
 	[ -n "$package_name" ] &&
 		{
 			# HTTP is proxy cache friendly
-			sed -i 's/^\(Source[^ ]*:[ \t]*\)https/\1http/g' "$(grep http -rl "$spec_dir/${package_name}.spec")"
+			sed -i 's/^\(Source[^ ]*:[ \t]*\)https/\1http/g' "$(grep http -rl "$spec_dir/"*.spec)"
 		}
 	# Install build depends
 	yum-builddep -y "$spec_dir"/*.spec || die "failed to solve dependencies"
 	# Download tar.gz to default path ${HOME}/rpmbuild/SOURCE
 	[ -n "$package_name" ] &&
 		{
-			spectool -g -R "$spec_dir/${package_name}.spec" || die "failed to download source file"
+			spectool -g -R "$spec_dir/"*.spec || die "failed to download source file"
 		}
 	# Building rpm or srpm packages
 	rpmbuild -ba "$spec_dir"/*.spec || die "failed to build rpms"
