tests/stress-ng: format filesystem with -O verity when test verity
"To create verity files on an ext4 filesystem,
the filesystem must have been formatted with -O verity"

Link: https://www.kernel.org/doc/html/v5.9/filesystems/fsverity.html#filesystem-support
Signed-off-by: Ma Xinjian <xinjianx.ma@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/stress-ng b/tests/stress-ng
--- a/tests/stress-ng
+++ b/tests/stress-ng
@@ -10,6 +10,10 @@ mount_dev()
 
 	[ $nr_partitions -ge 1 ] || die "nr_partitions is less than 1"
 	partition=${partitions%% *}
+	if [ "$test" = "verity" ]; then
+		log_cmd umount $partition
+		log_cmd mkfs.$fs -q -F -O verity $partition || die "fail to mkfs.$fs -q -F -O verity $partition"
+	fi
 
 	log_cmd mkdir -p $mnt
 	log_cmd mount $partition $mnt 2>/dev/null
