tests/stutter: add more log check
treat the following log as fail

lizhijian@inn:/result/stutter/2x-1HDD-ext4/lkp-snb01/debian-x86_64-2016-08-31.cgz/x86_64-kexec/gcc-6/d5adbfcd5f7bcc6fa58a41c5c5ada0e5c826ce2c/7$ cat log_result/dd-1.log
cp: error writing '/fs/sda2/ddfile': No space left on device

Signed-off-by: Li Zhijian <zhijianx.li@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/stutter b/tests/stutter
--- a/tests/stutter
+++ b/tests/stutter
@@ -16,8 +16,17 @@ log_cmd mkdir -p $LOGDIR_RESULTS
 log_eval export TESTDISK_DIR="${mount_points%% *}"
 
 log_cmd ./run.sh
-if [ $? -ne 0 ]; then
-	echo "run_fail: 1"
+ret=$?
+
+# This case reuqires disk_size > (system memory * 2 * 2), but it seems lkp has
+# not an existed filter to handle it, so here is to check whether there is a
+# 'No space left on device' error
+grep 'No space left on device' $LOGDIR_RESULTS/*.log && ret=1
+
+if [ $ret -ne 0 ]; then
+	echo "stutter: fail"
 else
-	echo "# run success"
+	echo "stutter: pass"
 fi
+
+exit $ret
