tests/test_bpf: fix no reproduce.sh
------
root@lkp-boy:~/lkp-tests# lkp run ./test_bpf-non-jit.yaml
2019-07-10 14:39:40 modprobe test_bpf
[snip]
root@lkp-boy:/lkp/result/test_bpf/non-jit/lkp-boy/debian/x86_64-rhel-7.6/gcc-7/4.9.0-1-amd64/3# cat reproduce.sh
 "modprobe" "test_bpf"
 "sleep" "10"
 "dmesg"
 "tail" "-1000"
------

reproduce.sh works, could run test again.
------
root@lkp-boy:/lkp/result/test_bpf/non-jit/lkp-boy/debian/x86_64-rhel-7.6/gcc-7/4.9.0-1-amd64/4# ./reproduce.sh
[snip]
[684349.543065] test_bpf: #301 MOD default X jited:0 10 PASS
[684349.543282] test_bpf: #302 MOD default A jited:0 16 PASS
[684349.543554] test_bpf: #303 JMP EQ default A jited:0 12 PASS
[684349.543807] test_bpf: #304 JMP EQ default X jited:0 12 PASS
[684349.544056] test_bpf: Summary: 305 PASSED, 0 FAILED, [0/297 JIT'ed]
------

Signed-off-by: Liu Yiding <yidingx.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/test_bpf b/tests/test_bpf
--- a/tests/test_bpf
+++ b/tests/test_bpf
@@ -4,12 +4,12 @@
 . $LKP_SRC/lib/debug.sh
 
 if [ "$test" = "jit" ]; then
-	sysctl net.core.bpf_jit_enable=1 || die "setup bpf_jit failed"
+	log_cmd sysctl net.core.bpf_jit_enable=1 || die "setup bpf_jit failed"
 
-	modprobe test_bpf
+	log_cmd modprobe test_bpf
 	exit_value=$?
 elif [ "$test" = "non-jit" ]; then
-	modprobe test_bpf
+	log_cmd modprobe test_bpf
 	exit_value=$?
 else
 	die "Parameter \"test\" is wrong"
@@ -18,8 +18,8 @@ fi
 # there are mainly two reasons for "sleep 5" is here:
 # - extent runtime
 # - give a buffer time so that relevant info be fully written to dmesg
-sleep 10
+log_cmd sleep 10
 
-dmesg | tail -1000
+log_cmd dmesg | log_cmd tail -1000
 
 exit $exit_value
