remove clearlinux support
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/xfstests b/tests/xfstests
--- a/tests/xfstests
+++ b/tests/xfstests
@@ -17,20 +17,8 @@ check_add_user()
 {
 	[ "x$1" != "x" ] || return
 	grep -q -w "$1" /etc/passwd && return
-	# 123456-fsgqa is a invalid user name on Clear, useradd doesn't work
-	useradd -m "$1" >/dev/null 2>&1 || {
-		if is_clearlinux; then
-			mkdir /home/$1
-			echo "$1:x:666" >> /etc/group
-			echo "$1:x:666:666::/home/$1:/bin/bash" >> /etc/passwd
-			# avoid error "su: Authentication service cannot retrieve authentication info"
-			echo "$1:!:17884::::::" >> /etc/shadow
-			chown -R $1:$1 /home/$1
-			chmod -R go= /home/$1
-		else
-			echo "$(basename $0): useradd $1 failed" 1>&2
-		fi
-	}
+
+	useradd -m "$1" >/dev/null 2>&1 || echo "$(basename $0): useradd $1 failed" 1>&2
 }
 
 create_virtual_disk()
