xfstests: fix tests generic/407 generic/408 on xfs
fix the following issue:
--------------
generic/407  [not run] Reflink not supported by test filesystem type: xfs
generic/408  [not run] Dedupe not supported by test filesystem type: xfs
--------------

Signed-off-by: Chen Rong <rongx.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/tests/xfstests b/tests/xfstests
--- a/tests/xfstests
+++ b/tests/xfstests
@@ -94,6 +94,10 @@ set_env()
 	[ "$test" = "xfs-244" ] && log_eval export MKFS_OPTIONS="-mcrc=0"
 	[ "$test" = "xfs-132" ] && (mkfs.xfs -f -mreflink=1 $TEST_DEV || die "mkfs.xfs test_dev failed")
 
+	if [ "$fs" = xfs ] && [ "${test%?}" = "generic-group" ]; then
+		mkfs.xfs -f -mreflink=1 $TEST_DEV || die "mkfs.xfs test_dev failed"
+	fi
+
 	[ "$test" = "generic-387" ] && {
 		printf "n\np\n1\n\n+1G\nw\n" | fdisk $SCRATCH_DEV
 		log_eval export SCRATCH_DEV="$SCRATCH_DEV"1
