monitors: return die if perf command failed
perf can take effect on the performance results of testsuites.

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/monitors/perf-probe b/monitors/perf-probe
--- a/monitors/perf-probe
+++ b/monitors/perf-probe
@@ -13,6 +13,7 @@ echo sym-offset	> $TRACING_ROOT/trace_options
 echo sym-addr	> $TRACING_ROOT/trace_options
 echo stacktrace	> $TRACING_ROOT/trace_options
 
+$perf -v || die 'perf command failed'
 for event in $events
 do
 	$perf probe $event
