watchdog: fix killing myself
This box is up running for 15 hours.

root@lkp-sb02 ~# w
 15:00:05 up  2:36,  1 user,  load average: 9.22, 9.11, 8.55
 USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
 root     pts/0    10.254.210.172   14:59    2.00s  0.00s  0.00s w

Why the watchdog does not reboot the machine?  Root cause is

Jun 19 13:25:15 lkp-sb02 systemd[1]: Received SIGCHLD from PID 463 (watchdog).
Jun 19 13:25:15 lkp-sb02 systemd[1]: Child 463 (watchdog) died (code=killed, status=15/TERM)
Jun 19 13:25:15 lkp-sb02 systemd[1]: Received SIGCHLD from PID 450 (watch-oom).
Jun 19 13:25:15 lkp-sb02 systemd[1]: Child 450 (watch-oom) died (code=killed, status=15/TERM)
Jun 19 13:25:15 lkp-sb02 systemd[1]: Received SIGCHLD from PID 469 (cat-watchdog).
Jun 19 13:25:15 lkp-sb02 systemd[1]: Child 469 (cat-watchdog) died (code=exited, status=0/SUCCESS)

Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>

diff --git a/monitors/watchdog b/monitors/watchdog
--- a/monitors/watchdog
+++ b/monitors/watchdog
@@ -67,19 +67,28 @@ else
 	wait_post_test --timeout $max_uptime && exit 0
 fi
 
+echo 'detected soft_timeout'
 touch $TMP/soft_timeout
 touch $RESULT_ROOT/soft_timeout
 
 # try to unblock the main shell, which will copy files to
 # $RESULT_ROOT, which helps debug the hang reason
-kill $(cat $TMP/pid-* /dev/null) 2>/dev/null
-sleep 3
-kill -9 $(cat $TMP/pid-* /dev/null) 2>/dev/null
+kill_tests
 
-# reboot it the hard way, if the main shell failed to reboot
-sleep 3m && {
-	echo w > /proc/sysrq-trigger
-	echo s > /proc/sysrq-trigger
-	sleep 10
-	echo b > /proc/sysrq-trigger
-}
+echo 'wait_post_test --timeout 60'
+wait_post_test --timeout 60 && exit 0
+
+# reboot it the hard way, if the main shell failed to kill me
+sleep 141 || exit
+
+test -f $TMP/job-finished && exit
+
+echo 'try to force reboot'
+reboot
+
+sleep 144 || exit
+
+echo w > /proc/sysrq-trigger
+echo s > /proc/sysrq-trigger
+sleep 10
+echo b > /proc/sysrq-trigger
