pack/hwsim: support WPA-EAP-SUITE-B-192
add "CONFIG_SUITEB192=y" build option for wpa_supplicant and hostapd

fix the following issue:
-----------------
Skip test case: WPA-EAP-SUITE-B-192 not supported
 hwsim.suite_b_192 					skip -> pass
 hwsim.suite_b_192_mic_failure				skip -> fail
 hwsim.suite_b_192_pmkid_failure			skip -> fail
 hwsim.suite_b_192_radius				skip -> pass
-----------------

Signed-off-by: Chen Rong <rongx.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/pack/hwsim b/pack/hwsim
--- a/pack/hwsim
+++ b/pack/hwsim
@@ -14,6 +14,27 @@ build()
 	make install || return
 	cd -
 	patch_source || return
+
+	# support WPA-EAP-SUITE-B-192, example-wpa_supplicant.config and example-hostapd.config contains support options for build.
+	# hostapd_config_parse_key_mgmt() in hostapd/config_file.c will check "CONFIG_SUITEB192".
+	# if not set "CONFIG_SUITEB192=y", suite_b_192 can not be added into key_mnt.
+
+	# if example-wpa_supplicant.config and example-hostapd.config not exist, it means hostap(git://w1.fi/srv/git/hostap.git)
+	# remove the files, we need to check the option in the new configuration files
+	local wpa_supplicant_config="./tests/hwsim/example-wpa_supplicant.config"
+	local hostapd_config="./tests/hwsim/example-hostapd.config"
+
+	if [[ -f $wpa_supplicant_config ]]; then
+		grep -q -w "CONFIG_SUITEB192=y" $wpa_supplicant_config || echo "CONFIG_SUITEB192=y" >> $wpa_supplicant_config
+	else
+		echo "Warning: $wpa_supplicant_config not exist, failed to set CONFIG_SUITEB192=y"
+	fi
+	if [[ -f $hostapd_config ]]; then
+		grep -q -w "CONFIG_SUITEB192=y" $hostapd_config || echo "CONFIG_SUITEB192=y" >> $hostapd_config
+	else
+		echo "Warning: $hostapd_config not exist, failed to set CONFIG_SUITEB192=y"
+	fi
+
 	$RUN_QUIET ./tests/hwsim/build.sh
 }
 
