pack/ltp: do not build with librpc-tirpc for some tests
fix the following issue:
---------------
rpc_svc_destroy 1 TFAIL: rpc_svc_destroy 10.0.0.2 536875000 failed unexpectedly
rpc_svcfd_create 1 TFAIL: rpc_svcfd_create 10.0.0.2 536875000 failed unexpectedly
rpc_xprt_register 1 TFAIL: rpc_xprt_register 10.0.0.2 536875000 failed unexpectedly
rpc_xprt_unregister 1 TFAIL: rpc_xprt_unregister 10.0.0.2 536875000 failed unexpectedly
---------------

Signed-off-by: Chen Rong <rongx.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/pack/ltp b/pack/ltp
--- a/pack/ltp
+++ b/pack/ltp
@@ -87,6 +87,19 @@ patch_source()
 	patch -p1 < $patch
 }
 
+rebuild()
+{
+	[ -d "$1" ] || return
+	local build_dir=$1
+	local current_dir=$(pwd)
+
+	cd $build_dir && {
+		make clean || return
+		make || return
+		cd $current_dir
+	}
+}
+
 build_rusers()
 {
 	local branch=$(git branch -a | grep /c | tail -1 | awk -F/ '{print $NF}')
@@ -140,7 +153,14 @@ build_ltp()
 	rearrange_case || return
 	make autotools
 	./configure --prefix=$BM_ROOT
-	make
+	make || return
+
+	# fix rpc test cases, linking to libtirpc-dev will make the tests failed in debian
+	sed -i "s/^LDLIBS/#LDLIBS/" testcases/network/rpc/rpc-tirpc/tests_pack/Makefile.inc || return
+	rebuild testcases/network/rpc/rpc-tirpc/tests_pack/rpc_suite/rpc/rpc_createdestroy_svc_destroy || return
+	rebuild testcases/network/rpc/rpc-tirpc/tests_pack/rpc_suite/rpc/rpc_createdestroy_svcfd_create || return
+	rebuild testcases/network/rpc/rpc-tirpc/tests_pack/rpc_suite/rpc/rpc_regunreg_xprt_register || return
+	rebuild testcases/network/rpc/rpc-tirpc/tests_pack/rpc_suite/rpc/rpc_regunreg_xprt_unregister
 }
 
 build_numactl()
