lkp-exec/install: only use makepkg to install benchmark if adapted
Only use makepkg to install benchmark if there exists adaptation in
adaptation-pkg.
Avoid installing same conflict package when the package exists in the
repo

Signed-off-by: Wu Chenggang <chenggang.wu@intel.com>
Reviewed-by: "Huang, Ying" <ying.huang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/lkp-exec/install b/lkp-exec/install
--- a/lkp-exec/install
+++ b/lkp-exec/install
@@ -183,7 +183,9 @@ makepkg_install_packages() {
 
 makepkg_install_benchmark() {
 	local pkg=$1
-	makepkg_install "$pkg" || echo "Install $pkg failed"
+	if grep "$pkg::" "$LKP_SRC/distro/adaptation-pkg/$distro"; then
+		makepkg_install "$pkg" || echo "Install $pkg failed"
+	fi
 }
 
 install_packages() {
