lkp-exec/install: create lkp account per user's agreement
Signed-off-by: Hailin Gu <hailinx.gu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/lkp-exec/install b/lkp-exec/install
--- a/lkp-exec/install
+++ b/lkp-exec/install
@@ -71,6 +71,27 @@ make_wakeup() {
 	}
 }
 
+create_lkp_user() {
+	grep -q ^lkp: /etc/passwd && return
+
+	echo -n "Do you agree to create lkp users for testing? [N/y]"
+	read input
+	case $input in
+		Y|y)
+			useradd -m -s /bin/bash lkp
+			if [ $? -eq 0 ]; then
+				echo "Create lkp user successfully."
+			else
+				echo "Create lkp user failed."
+				exit 1
+			fi
+		;;
+		*)
+			echo "Skip to create user steps."
+		;;
+	esac
+}
+
 # todo: make paths configurable and less intrusive to developer's system
 # currently it's hard coded in a number of places, should be changed together
 create_lkp_dirs() {
@@ -244,6 +265,7 @@ else
 fi
 
 make_wakeup
+create_lkp_user
 create_lkp_dirs
 create_host_config
 
