lkp-exec/rm-path: skip bad reprocess paths to avoid revert_unite_rt hangs
2021-08-26 16:31:55 +0800 INFO LKP_HOME=/lkp/rongc /lkp/rongc/src/bin/lkp rm-path -y /result/boot/1/vm-snb/aliyun-x86_64-20190626.cgz/x86_64-kexec/gcc-9/425fdf2935be98739ab09a0e4ef1214bea6b2a8d/1
lkp reprocess -d /result/boot/1/vm-snb/aliyun-x86_64-20190626.cgz/x86_64-kexec/gcc-9/4056eec6f9c8dd0c32fce7ddac622d3af84576f4/0
The command to remove the result path are:
rm -fr /result/boot/1/vm-snb/aliyun-x86_64-20190626.cgz/x86_64-kexec/gcc-9/425fdf2935be98739ab09a0e4ef1214bea6b2a8d/1
lkp reprocess -d /result/boot/1/vm-snb/aliyun-x86_64-20190626.cgz/x86_64-kexec/gcc-9/425fdf2935be98739ab09a0e4ef1214bea6b2a8d/1
'/lkp/rongc/results_to_process/__result__sha1__06bbcba900e955695348a0ac59cd696e8c309ce7delete' -> '/result/boot/1/vm-snb/aliyun-x86_64-20190626.cgz/x86_64-kexec/gcc-9/4056eec6f9c8dd0c32fce7ddac622d3af84576f4/0'
/result/boot/1/vm-snb/aliyun-x86_64-20190626.cgz/x86_64-kexec/gcc-9/4056eec6f9c8dd0c32fce7ddac622d3af84576f4/0
failed to reprocess /result/boot/1/vm-snb/aliyun-x86_64-20190626.cgz/x86_64-kexec/gcc-9/425fdf2935be98739ab09a0e4ef1214bea6b2a8d/1

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/lkp-exec/rm-path b/lkp-exec/rm-path
--- a/lkp-exec/rm-path
+++ b/lkp-exec/rm-path
@@ -74,18 +74,25 @@ remove_from_mrtts()
 
 revert_unite_rt()
 {
+	local bad_paths=()
+
 	local path
 	for path; do
 		if is_rt "$path" && check_rt "$path"; then
 			if is_local_run "$path"; then
 				$LKP_SRC/sbin/unite-stats -d "$path"
 			else
-				lkp reprocess -d "$path"
+				echo lkp reprocess -d "$path"
+				lkp reprocess -d "$path" | grep "results_to_process" || {
+					echo "failed to reprocess $path"
+					bad_paths+=($path)
+				}
 			fi
 		fi
 	done
 
 	for path; do
+		[[ " ${bad_paths[*]} " =~ " $path " ]] && continue
 		while is_rt "$path" && check_rt "$path" && ! is_local_run "$path"; do
 			sleep 10
 		done
