setup/boot_params: bug fix
fix the bug that can't match parameters contains special characters.

Signed-off-by: Wu Chenggang <chenggang.wu@intel.com>
Reviewed-by: "Huang, Ying" <ying.huang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/setup/boot_params b/setup/boot_params
--- a/setup/boot_params
+++ b/setup/boot_params
@@ -9,7 +9,7 @@
 # - bp_maxcpus
 
 # Kernel boot parameters that will impact performance/power
-cmdline=$(cat /proc/cmdline)
+cmdline=" $(cat /proc/cmdline) "
 
 check_param()
 {
@@ -18,8 +18,8 @@ check_param()
 	if [ "$value" != "null_boot_param" ]; then
 		param_str="${param#*_}"
 		[ -n "$value" ] && param_str="$param_str=$value"
-		if ! echo "$cmdline" | grep -q "\b$param_str\b"; then
-			echo "Missing parameter: $param_str, actual command line: $cmdline"
+		if ! echo "$cmdline" | grep -qF " $param_str "; then
+			echo "Missing parameter: $param_str, actual command line:$cmdline"
 			exit 1
 		fi
 	fi
