setup/disk: Check for invalid partitions configuration
To fix bug as below,

/lkp/lkp/src/setup/fio-setup-basic: arithmetic expression: division by zero: "nr_task / nr_storages"

Signed-off-by: Huang Ying <ying.huang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/setup/disk b/setup/disk
--- a/setup/disk
+++ b/setup/disk
@@ -32,6 +32,16 @@ check_nr_partitions()
 		return 1
 	}
 
+	[ -n "$nr_hdd_partitions" ] && [ -z "$hdd_partitions" ] && {
+		echo "Invalid hdd disk configuration, please check host file!" >&2
+		return 1
+	}
+
+	[ -n "$nr_ssd_partitions" ] && [ -z "$ssd_partitions" ] && {
+		echo "Invalid ssd disk configuration, please check host file!" >&2
+		return 1
+	}
+
 	return 0
 }
 
