md: Try more md device number
For OLT-985, to fix the following error

016-04-11 19:07:23.406950500 [lkp process-result-queue 62434] /result/aim7/4BRD_12G-RAID0-xfs-3000-disk_rr/ivb44/debian-x86_64-2015-02-07.cgz/x86_64-rhel/gcc-4.9/bf16200689118d19de1b8d2a3c314fc21f5dc7bb/0/stderr:
2016-04-11 19:07:23.407117500 [lkp process-result-queue 62434] stderr: mdadm: /dev/md0 is already in use.
2016-04-11 19:07:23.407126500 [lkp process-result-queue 62434] stderr: can't get size of data subvolume
2016-04-11 19:07:23.407179500 [lkp process-result-queue 62434] stderr: Usage: mkfs.xfs
2016-04-11 19:07:23.407195500 [lkp process-result-queue 62434] stderr: /* blocksize */          [-b log=n|size=num]
2016-04-11 19:07:23.407245500 [lkp process-result-queue 62434] stderr: /* metadata */           [-m crc=0|1,finobt=0|1]
2016-04-11 19:07:23.407253500 [lkp process-result-queue 62434] stderr: /* data subvol */        [-d agcount=n,agsize=n,file,name=xxx,size=num,
2016-04-11 19:07:23.407306500 [lkp process-result-queue 62434] stderr: (sunit=value,swidth=value|su=num,sw=num|noalign),
2016-04-11 19:07:23.407315500 [lkp process-result-queue 62434] stderr: sectlog=n|sectsize=num
2016-04-11 19:07:23.407416500 [lkp process-result-queue 62434] stderr: /* force overwrite */    [-f]
2016-04-11 19:07:23.407417500 [lkp process-result-queue 62434] stderr: /* inode size */ [-i log=n|perblock=n|size=num,maxpct=n,attr=0|1|2,

It appears that the machine has hard disk which is formatted to RAID
mode, but doesn't initialized successfully during boot.  So cause
ramdisk RAID initialization failed too because of conflict raid device
number.  Fix this via trying other raid device number.

Signed-off-by: Huang Ying <ying.huang@intel.com>
Signed-off-by: Fengguang Wu <fengguang.wu@intel.com>

diff --git a/setup/md b/setup/md
--- a/setup/md
+++ b/setup/md
@@ -44,17 +44,23 @@ check_partition_size $partitions
 make_md() {
 	grep -q '^md0 : active' /proc/mdstat && cmd mdadm -q --stop /dev/md0
 	destroy_devices
-	echo y | cmd mdadm -q --create /dev/md0 --chunk=$raid_chunk --level=$raid_level --raid-devices=$nr_partitions --force --assume-clean $partitions
+	for i in 0 1 2 3 4 5; do
+		raid_device=/dev/md$i
+		echo y | cmd mdadm -q --create $raid_device --chunk=$raid_chunk --level=$raid_level --raid-devices=$nr_partitions --force --assume-clean $partitions 2> /tmp/mdadm_stderr && return
+	done
+	echo "Failed to create RAID!" 1>&2
+	cat /tmp/mdadm_stderr 1>&2
+	exit 1
 }
 
-make_md || make_md
+make_md
 
 cat >> $TMP/env.yaml <<EOF
 
 # setup/md
 nr_partitions: 1
-partitions: /dev/md0
-raid_device: /dev/md0
+partitions: $raid_device
+raid_device: $raid_device
 raid_level: $raid_level
 raid_chunk: $raid_chunk
 EOF
