jobs/oltp.yaml: test oltp on a physical disk
The oltp running with ramdisk is not the usual case that other people are running,
and we may miss some performance changes.

Signed-off-by: Chen Rong <rong.a.chen@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/setup/mysql-setup b/setup/mysql-setup
--- a/setup/mysql-setup
+++ b/setup/mysql-setup
@@ -2,12 +2,8 @@
 
 setup_mysql()
 {
+	local mnt_point=$1
 	systemctl stop mariadb.service
-
-	# datadir in rootfs too small to meet mysql requriments
-	# /etc/init.d/mysql: ERROR: The partition with /lkp/lkp/src/tmp/mysql is too full! ... failed!
-	mkdir -p $TMP/mysql
-	mount -t tmpfs mysql $TMP/mysql
 
 	# fix "Neither host 'lkp-bdw-ex1' nor 'localhost'
 	# could be looked up with '/usr/sbin/resolveip'"
@@ -15,7 +11,8 @@ setup_mysql()
 	[ ! -x /usr/sbin/resolveip ] && \
 	ln -s $(which resolveip) /usr/sbin/resolveip
 
-	mysql_install_db --datadir="$TMP/mysql" --user=mysql
+	mkdir -p $mnt_point/mysql
+	mysql_install_db --datadir="$mnt_point/mysql" --user=mysql
 
 	# fix "FATAL: error 1040: Too many connections"
 	local max_conn=100
@@ -30,7 +27,10 @@ setup_mysql()
 	# /usr/bin/haswell/mysql is used on Clear Linux
 	local exec_mysqld='mysqld'
 	mysqld --version >/dev/null 2>&1 || exec_mysqld='/usr/libexec/mysqld'
-	$exec_mysqld --datadir="$TMP/mysql" --max-connections="$max_conn" --skip-grant-tables --user=mysql &
+	$exec_mysqld --datadir="$mnt_point/mysql" --max-connections="$max_conn" --skip-grant-tables --user=mysql &
 }
 
-setup_mysql
+[ -n "$mount_points" ] || { echo "empty mount_points, disk failed?" >&2; exit; }
+
+mnt_point="${mount_points%% *}"
+setup_mysql "$mnt_point"
