bootstrap.sh: add swap partition when testbox have $rootfs_disk
[Why]
In some case, memory is not enough for test, so we need to use swap to
increase the fault tolerance of the test job when testbox have
$rootfs_disk.

[How]
if your testbox have $rootfs_disk, then you can add the following field
in your job.yaml, then your testbox will have at least 8g swap space:
    swap:

[Addition]
if your testbox have $rootfs_disk:
- if your job.yaml only have 'swap:', then your job will get 8g swap
  partition.
- if your job.yaml both have 'swap:' and 'disk: XHDD', then your job
  will use all XHDD as swap partition.

Signed-off-by: Yu Chuan <13186087857@163.com>

diff --git a/setup/swap b/setup/swap
--- a/setup/swap
+++ b/setup/swap
@@ -5,8 +5,35 @@
 . "$LKP_SRC"/lib/common.sh
 . "$LKP_SRC"/lib/reproduce-log.sh
 
+config_swap_partition()
+{
+	local vg_name=os
+	vgdisplay $vg_name > /dev/null || {
+		echo "cannot find vg: $vg_name"
+		exit 1
+	}
+
+	local swap_lv=/dev/mapper/${vg_name}-swap
+	[ -b "$swap_lv" ] && lvremove --force $swap_lv
+	lvcreate -y -L 8G --name swap "$vg_name" || {
+		echo "lvcreate failed: swap"
+		exit 1
+	}
+
+	mkswap -f $swap_lv && swapon $swap_lv || {
+		echo "prepare swap failed."
+		exit 1
+	}
+}
+
+# if have $rootfs_disk, then 'swap' field will create a swap lv(8G) and use it as swap partition.
+[ -n "$rootfs_disk" ] && config_swap_partition
+
 if [ -z "$partitions" ]; then
 	echo "no partitions found" >&2
+
+	# if have $rootfs_disk, then exit 0
+	[ -n "$rootfs_disk" ] && exit 0
 	exit 1
 fi
 
