install deb packages according to apt install dependency
To fix the following error:
--------
root@xps ~# dpkg -i gawk_1%3a4.1.4+dfsg-1_amd64.deb libreadline7_7.0-2_amd64.deb
dpkg: regarding gawk_1%3a4.1.4+dfsg-1_amd64.deb containing gawk, pre-dependency problem:          <======
 gawk pre-depends on libreadline7 (>= 6.0)
  libreadline7 is not installed.
--------
due to gawk*.deb's sort is in front of libreadline7*.deb, "gwak" pkg including "pre-dependency" definition.
the deb package installation sequence is necessary, and this sequence should be automatically generated rather than manually maintained.
so we adjust the install flow as:
   step 1 generate /opt/deb/sequence-deb by $PACKAGE_LIST and $LKP_SRC/distro/keep-deb
   step 2 generate /opt/deb/keep-deb by /opt/deb/sequence-deb
   step 3 tbox uses /opt/deb/keep-deb list to install deb from /opt/deb

Signed-off-by: Hailin Gu <hailinx.gu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>

diff --git a/distro/debian b/distro/debian
--- a/distro/debian
+++ b/distro/debian
@@ -31,15 +31,39 @@ hardlink_to_symlink()
 
 install()
 {
+	local deb_pkgname
+	local deb_filename
+	local deb_files
+
+	# sequence-deb content looks like:
+	#   libreadline7
+	#   libssl1.1
+	#   gawk
+	[ -s "opt/deb/sequence-deb" ] && {
+		deb_files=$(find ./ -name "*.deb" -type f)
+		while read -r deb_pkgname
+		do
+			# deb package naming specification, the file name must contain '_'
+			deb_filename=$(echo "$deb_files" | grep "^\./${deb_pkgname}_")
+			if [ -n "${deb_filename}" ]; then
+				mv "$deb_filename"  opt/deb
+
+				# keep-deb content looks like:
+				#   libreadline7_7.0-1_amd64.deb
+				#   libssl1.1_1.1.0d-2_amd64.deb
+				#   gawk_1%3a4.1.3+dfsg-0.1+b1_amd64.deb
+				echo $(basename $deb_filename) >> opt/deb/keep-deb
+			else
+				echo "error: $deb_filename is not exist." >&2
+				return 1
+			fi
+		done < opt/deb/sequence-deb
+	}
+
 	local deb
 	for deb in *.deb; do
-		if echo "$deb" | grep -q -F -f $LKP_SRC/distro/keep-deb; then
-			mkdir -p opt/deb
-			mv "$deb"  opt/deb
-		else
-			dpkg-deb -x "$deb" . || return
-			rm "$deb"
-		fi
+		dpkg-deb -x "$deb" . || return
+		rm "$deb"
 	done
 
 	hardlink_to_symlink
